### ISSUE TITLE
ExampleMinimal throws exception on app quit (MacOS)

### ISSUE THREAD

**Issue by bparvanov** [HexaEngine/Hexa.NET.KittyUI#5]
System.Exception: Unknown touch device id -1, cannot reset
   at Hexa.NET.Logging.Logger.Throw(Exception exception)
   at Hexa.NET.Logging.Logger.ThrowIfNotNull(Exception exception)
   at Hexa.NET.KittyUI.Windows.CoreWindow.DestroyWindow(Boolean appClose) in /Users/borislav/Projects/Hexa.NET.KittyUI/Hexa.NET.KittyUI/Windows/CoreWindow.cs:line 1324
   at Hexa.NET.KittyUI.Application.PlatformRun() in /Users/borislav/Projects/Hexa.NET.KittyUI/Hexa.NET.KittyUI/Application.cs:line 173
   at Hexa.NET.KittyUI.Application.Run(IRenderWindow mainWindow, AppBuilder builder) in /Users/borislav/Projects/Hexa.NET.KittyUI/Hexa.NET.KittyUI/Application.cs:line 56
   at Hexa.NET.KittyUI.AppBuilder.Run() in /Users/borislav/Projects/Hexa.NET.KittyUI/Hexa.NET.KittyUI/AppBuilder.cs:line 31
   at Program.<Main>$(String[] args) in /Users/borislav/Projects/Hexa.NET.KittyUI/ExampleMinimal/Program.cs:line 9

**Comment by JunaMeinhold** [comment]
A weird place to happen that's the thing.

When a crash happens the framework generates crash files btw, in the logs folder.

**Comment by bparvanov** [comment]
In the .log file there is only one line:
10:45 [Error] [SDL] System.Exception: Unknown touch device id -1, cannot reset

I found this:
https://stackoverflow.com/questions/63983054/sdl-geterror-returning-an-undocumented-error-on-macos

**Comment by JunaMeinhold** [comment]
I think this should fix it then
![image](https://github.com/user-attachments/assets/22d1474c-cc34-4802-b5b6-23270baa563e)

**Comment by bparvanov** [comment]
Unfortunately still happens.. I noticed that it throws on quit only if I clicked at least once in the window's client area... If I just close the window without clicking inside it, it doesn't crash.

**Comment by JunaMeinhold** [comment]
Still the same error? if yes i will just remove the error check before quitting, it's probably for the best since SDL2 docs say GetError should not be used to determine if a error happened.

**Comment by bparvanov** [comment]
Yes, same error

**Comment by JunaMeinhold** [comment]
I think this should fix it.

**Comment by bparvanov** [comment]
Yes, it doesn't crash anymore
